name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pytest pytest-html

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest --html=report.html -p no:warnings
          
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: report.html
